name: Datree-policy-Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  ArgoCDPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'Deployments/K8s/argocd.yaml'
          cliArguments: '--only-k8s-files -p Argo'